# Generated by Django 4.2.5 on 2023-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='descricao',
            field=models.TextField(default='Estou usando precifica aí para precificar minhas receitas!'),
        ),
    ]
