# Generated by Django 4.2.5 on 2023-09-19 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0002_receita_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade_embalagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_embalagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precificacao.receita')),
            ],
        ),
    ]
